FORMAT: 1A
HOST: http://private-4e69c-nihimoto1.apiary-mock.com/

# toast music

試し書き中

##  ログイン


## Live [/lives]

### List All Lives [GET]

+ Request

+ Response 200 (application/json)
    + Attributes(live)

+ Response 401 (text/plain)

        There is no such a message for you, dear guest.


## オススメ：AppleMusic [/recomend/apple_music]

TODO

## オススメ：Soitify [/recomend/spotify]

TODO

## オススメ：Twitter [/recomend/twitter]

TODO

## コピペ用 [/hoge]

ドキュメント記述時のコピペ用に置いているダミーです

### Sample [GET]

+ Request
    + Attributes (Sample2)

+ Response 200 (application/json)

    + Headers
            Location: /questions/1
    + Attributes (Sample1)


+ Response 401 (text/plain)

        There is no such a message for you, dear guest.

# Data Structures

## live
+ id: `999` (number) - primary key
+ origin: `eplus` (string) - ライブ情報取得元サイト eplus, pla, ... TODO 値リスト
+ show_start_at: `July 19, 2018 18:30` (string) - 公演開始日時 TODO 意味あってる？／日付形式要確認
+ doors_open_at: `July 19, 2018 18:00` (string) - 開場開始日時 TODO 意味あってる？／日付形式要確認
+ venue: `新宿RUIDO.K4` (string) - 会場名
+ prefecture: `東京都` (string) - 都道府県 TODO IDなどではなく日本語テキスト？
+ venue_detail_id: `999` (number) - 会場ID
+ venue_detail (venueDetail)
+ admin_status: `1` (number) - 管理ステータス？ TODO これは何？
+ created_at: `June 23, 2018 08:43` (string) - 登録日時 TODO 日付形式要確認
+ updated_at: `June 23, 2018 08:43` (string) - 更新日時 TODO 日付形式要確認

## venue

## venueDetail
+ id: `999` (number) - primary key

## ticket


## user


## Sample1
+ email: `foo@bar.com` (string) - Email Adress
+ password: `secret` (string) -Password
+ choices (array[Sample2], required)

## Sample2
+ email2: `foo@bar.com` (string) - Email Adress
+ password2: `secret` (string) -Password